export const HaproxySections: { [key: string]: string } = {
  global: 'global',
  defaults: 'defaults',
  listen: 'listen',
  frontend: 'frontend',
  backend: 'backend'
};

export const HaproxySectionsList: Array<string> = [
  HaproxySections.global,
  HaproxySections.defaults,
  HaproxySections.listen,
  HaproxySections.frontend,
  HaproxySections.backend,
];

export const HaproxyCustomSections: { [key: string]: string } = {
  global: 'global',
  defaults: 'defaults',
  listen: 'listeners',
  frontend: 'frontends',
  backend: 'backends'
};

export const HaproxyCustomSectionsList: Array<string> = [
  HaproxyCustomSections.global,
  HaproxyCustomSections.defaults,
  HaproxyCustomSections.listen,
  HaproxyCustomSections.frontend,
  HaproxyCustomSections.backend
];

export const HaproxyOptions: { [key: string]: string } = {
  acl: 'acl',
  appsession: 'appsession',
  backlog: 'backlog',
  balance: 'balance',
  bind: 'bind',
  'bind-process': 'bind-process',
  block: 'block',
  capture: 'capture',
  clitimeout: 'clitimeout',
  contimeout: 'contimeout',
  cookie: 'cookie',
  'default-server': 'default-server',
  default_backend: 'default_backend',
  description: 'description',
  disabled: 'disabled',
  dispatch: 'dispatch',
  enabled: 'enabled',
  errorfile: 'errorfile',
  errorloc: 'errorloc',
  errorloc302: 'errorloc302',
  errorloc303: 'errorloc303',
  'force-persist': 'force-persist',
  fullconn: 'fullconn',
  grace: 'grace',
  'hash-type': 'hash-type',
  'http-check': 'http-check',
  'http-request': 'http-request',
  id: 'id',
  'ignore-persist': 'ignore-persist',
  log: 'log',
  maxconn: 'maxconn',
  mode: 'mode',
  monitor: 'monitor',
  'monitor-net': 'monitor-net',
  'monitor-uri': 'monitor-uri',
  option: 'option',
  persist: 'persist',
  'rate-limit': 'rate-limit',
  redirect: 'redirect',
  redisp: 'redisp',
  redispatch: 'redispatch',
  reqadd: 'reqadd',
  reqallow: 'reqallow',
  reqdel: 'reqdel',
  reqdeny: 'reqdeny',
  reqiallow: 'reqiallow',
  reqidel: 'reqidel',
  reqideny: 'reqideny',
  reqipass: 'reqipass',
  reqirep: 'reqirep',
  reqisetbe: 'reqisetbe',
  reqitarpit: 'reqitarpit',
  reqpass: 'reqpass',
  reqrep: 'reqrep',
  reqsetbe: 'reqsetbe',
  reqtarpit: 'reqtarpit',
  retries: 'retries',
  rspadd: 'rspadd',
  rspdel: 'rspdel',
  rspdeny: 'rspdeny',
  rspidel: 'rspidel',
  rspideny: 'rspideny',
  rspirep: 'rspirep',
  rsprep: 'rsprep',
  server: 'server',
  source: 'source',
  srvtimeout: 'srvtimeout',
  stats: 'stats',
  stick: 'stick',
  'stick-table': 'stick-table',
  'tcp-request': 'tcp-request',
  timeout: 'timeout',
  transparent: 'transparent',
  use_backend: 'use_backend'
};


export const HaproxyOptionsList: Array<string> = [
  HaproxyOptions.acl,
  HaproxyOptions.appsession,
  HaproxyOptions.backlog,
  HaproxyOptions.balance,
  HaproxyOptions.bind,
  HaproxyOptions['bind-process'],
  HaproxyOptions.block,
  HaproxyOptions.capture,
  HaproxyOptions.clitimeout,
  HaproxyOptions.contimeout,
  HaproxyOptions.cookie,
  HaproxyOptions['default-server'],
  HaproxyOptions.default_backend,
  HaproxyOptions.description,
  HaproxyOptions.disabled,
  HaproxyOptions.dispatch,
  HaproxyOptions.enabled,
  HaproxyOptions.errorfile,
  HaproxyOptions.errorloc,
  HaproxyOptions.errorloc302,
  HaproxyOptions.errorloc303,
  HaproxyOptions['force-persist'],
  HaproxyOptions.fullconn,
  HaproxyOptions.grace,
  HaproxyOptions['hash-type'],
  HaproxyOptions['http-check'],
  HaproxyOptions['http-request'],
  HaproxyOptions.id,
  HaproxyOptions['ignore-persist'],
  HaproxyOptions.log,
  HaproxyOptions.maxconn,
  HaproxyOptions.mode,
  HaproxyOptions.monitor,
  HaproxyOptions['monitor-net'],
  HaproxyOptions['monitor-uri'],
  HaproxyOptions.option,
  HaproxyOptions.persist,
  HaproxyOptions['rate-limit'],
  HaproxyOptions.redirect,
  HaproxyOptions.redisp,
  HaproxyOptions.redispatch,
  HaproxyOptions.reqadd,
  HaproxyOptions.reqallow,
  HaproxyOptions.reqdel,
  HaproxyOptions.reqdeny,
  HaproxyOptions.reqiallow,
  HaproxyOptions.reqidel,
  HaproxyOptions.reqideny,
  HaproxyOptions.reqipass,
  HaproxyOptions.reqirep,
  HaproxyOptions.reqisetbe,
  HaproxyOptions.reqitarpit,
  HaproxyOptions.reqpass,
  HaproxyOptions.reqrep,
  HaproxyOptions.reqsetbe,
  HaproxyOptions.reqtarpit,
  HaproxyOptions.retries,
  HaproxyOptions.rspadd,
  HaproxyOptions.rspdel,
  HaproxyOptions.rspdeny,
  HaproxyOptions.rspidel,
  HaproxyOptions.rspideny,
  HaproxyOptions.rspirep,
  HaproxyOptions.rsprep,
  HaproxyOptions.server,
  HaproxyOptions.source,
  HaproxyOptions.srvtimeout,
  HaproxyOptions.stats,
  HaproxyOptions.stick,
  HaproxyOptions['stick-table'],
  HaproxyOptions['tcp-request'],
  HaproxyOptions.timeout,
  HaproxyOptions.transparent,
  HaproxyOptions.use_backend
];

export const HaproxyCustomParsers: { [key: string]: string } = {
  capture: 'capture',
  errorfile: 'errorfile',
  'http-check': 'http-check',
  monitor: 'monitor',
  option: 'option',
  persist: 'persist',
  stats: 'stats',
  stick: 'stick',
  timeout: 'timeout'
};

export const HaproxyCustomParsersList: Array<string> = [
  HaproxyCustomParsers.capture,
  HaproxyCustomParsers.errorfile,
  HaproxyCustomParsers['http-check'],
  HaproxyCustomParsers.monitor,
  HaproxyCustomParsers.option,
  HaproxyCustomParsers.persist,
  HaproxyCustomParsers.stats,
  HaproxyCustomParsers.stick,
  HaproxyCustomParsers.timeout
];
